
[env]
TERM = "alacritty"

[window]
dynamic_padding = false
opacity = 0.85
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"


[window.padding]
x = 6
y = 6

[general]
import = ["/home/acph/.config/alacritty/themes/themes/horizon-dark.toml"]


[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"
