#!/bin/bash

pacman -S \
       emacs\
       alacritty\
       rofi\
       picom\
       qtile\
       awesome\
       htop\
       i3lock\
       flameshot\
       syncthing\
       easyeffects\
       ollama\
       ttf-fira-code\
       btop\
       bat\
       xclip\
       maim\
       otf-font-awesome\
       ttf-noto-nerd\
       hyprland\
       hyprpaper\
       xdg-desktop-portal-hyprland\
       waybar\
       swaync\
       hyprlock\
       grim
